### ISSUE TITLE
Backup when no secondaries available

### ISSUE THREAD

**Issue by klall** [knyar/mongoclusterscripts#1]
First of all thank you for writing this script, it is great for our project. 

Under normal circumstances the backups would only occur for secondaries. However, one question I have is about the situation when there are no good secondaries available:

https://github.com/knyar/mongoclusterscripts/blob/master/mongo-backup/mongoclusterbackup.py#L86

In that case the backup is performed on the primaries it seems. But if we lock the master then no writes can happen so the database would be in a read only mode right? That wouldn't be ideal in our environment. 

Just wanted to clarify the intent in that snippet of code.

Our environment is in AWS so I forked the script so I can modify it to do EC2 snapshots but thanks for an excellent starting point.

**Comment by knyar** [comment]
I understand that a reply more than a year after you asked might not be too useful, but I've just found this issue (sorry). Happy to hear that you found this piece of code useful.

I believe the intent was to make backup succeed even if it means locking one of the masters, but I agree that this would be undesirable for a production system. It seems that a better solution might be to not dump data at all, and exit with code > 0, which will hopefully raise an alert.

I am no longer running mongodb, so I don't think I will be able to improve this.
Again, apologies for a (very) delayed response.
